SELECT (23+((25-2)/2) *45) AS RESULTADO;

SELECT CEILING(12.33331213132) AS RESULT;

SELECT ROUND(12.33331213132) AS RESULT;

SELECT FLOOR(12.77777713132) AS RESULT;

SELECT RAND() AS RESULT;

SELECT NUMERO, QUANTIDADE, PRECO, ROUND(QUANTIDADE * PRECO, 2) AS FATURAMENTO FROM itens_notas_fiscais;


SELECT * FROM notas_fiscais;

SELECT * FROM itens_notas_fiscais;

SELECT A.NUMERO, A.IMPOSTO, B.QUANTIDADE, B.PRECO,
FLOOR((A.IMPOSTO * (B.QUANTIDADE * B.PRECO))) 
FROM notas_fiscais A, itens_notas_fiscais B
 WHERE YEAR(A.DATA_VENDA) = '2016'
ORDER BY A.NUMERO;

SELECT A.IMPOSTO, B. QUANTIDADE, B. PRECO FROM notas_fiscais A, itens_notas_fiscais B;


SELECT A.NUMERO, A.IMPOSTO, B.QUANTIDADE, B.PRECO,
FLOOR((A.IMPOSTO * (B.QUANTIDADE * B.PRECO))) as FATURAMENTO_2016
FROM notas_fiscais A, itens_notas_fiscais B
 WHERE YEAR(A.DATA_VENDA) = '2016'
ORDER BY A.NUMERO;

select A.NUMERO, A.IMPOSTO, B.QUANTIDADE, B.PRECO,
floor((A.IMPOSTO * (B.QUANTIDADE * B.PRECO))),(A.IMPOSTO * (B.QUANTIDADE * B.PRECO))
from notas_fiscais A, itens_notas_fiscais B
WHERE YEAR(A.DATA_VENDA) = '2016';


SELECT YEAR(DATA_VENDA), FLOOR(SUM(IMPOSTO * (QUANTIDADE * PRECO))) as FATURAMENTO
FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY YEAR(DATA_VENDA);